// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChBjvAEBhWl6XuBBD16UktKXlh1AMBNoU',
    appId: '1:297050045843:web:66e1b13861b4246c91fc66',
    messagingSenderId: '297050045843',
    projectId: 'eduvision-6ba8d',
    authDomain: 'eduvision-6ba8d.firebaseapp.com',
    storageBucket: 'eduvision-6ba8d.firebasestorage.app',
    measurementId: 'G-N1DZJ8S2NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChBjvAEBhWl6XuBBD16UktKXlh1AMBNoU',
    appId:
        '1:297050045843:android:xxxxx', // Will be replaced when you add Android app
    messagingSenderId: '297050045843',
    projectId: 'eduvision-6ba8d',
    storageBucket: 'eduvision-6ba8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChBjvAEBhWl6XuBBD16UktKXlh1AMBNoU',
    appId: '1:297050045843:ios:xxxxx', // Will be replaced when you add iOS app
    messagingSenderId: '297050045843',
    projectId: 'eduvision-6ba8d',
    storageBucket: 'eduvision-6ba8d.firebasestorage.app',
    iosClientId: 'xxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduvision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChBjvAEBhWl6XuBBD16UktKXlh1AMBNoU',
    appId:
        '1:297050045843:ios:xxxxx', // Will be replaced when you add macOS app
    messagingSenderId: '297050045843',
    projectId: 'eduvision-6ba8d',
    storageBucket: 'eduvision-6ba8d.firebasestorage.app',
    iosClientId: 'xxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduvision',
  );
}
