// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVision.Models;

public partial class GeneratedVideo
{
    public int GenerateVideoId { get; set; }

    public int? PromptId { get; set; }

    public int? SlideId { get; set; }

    public string Status { get; set; }

    public int? DurationSec { get; set; }

    public string Resolution { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string VideoUrl { get; set; }

    public int? UserId { get; set; }

    public virtual Prompt Prompt { get; set; }

    public virtual Slide Slide { get; set; }

    public virtual User User { get; set; }
}