// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVision.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? UserId { get; set; }

    public decimal? Amount { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string OrderCode { get; set; }

    public virtual User User { get; set; }


}