// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVision.Models;

public partial class Prompt
{
    public int Promptid { get; set; }

    public int? UserId { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Status { get; set; }

    public virtual ICollection<GeneratedVideo> GeneratedVideos { get; set; } = new List<GeneratedVideo>();

    public virtual ICollection<Slide> Slides { get; set; } = new List<Slide>();

    public virtual User User { get; set; }
}