// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVision.Models;

public partial class Slide
{
    public int SlideId { get; set; }

    public int? PromptId { get; set; }

    public int? UserId { get; set; }

    public string Type { get; set; }

    public string Url { get; set; }

    public string Status { get; set; }

    public virtual ICollection<GeneratedVideo> GeneratedVideos { get; set; } = new List<GeneratedVideo>();

    public virtual Prompt Prompt { get; set; }

    public virtual User User { get; set; }
}