// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVision.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public bool? IsVerified { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsActive { get; set; }

    public int Role { get; set; }

    public string FcmToken { get; set; }

    public string PhoneNumber { get; set; }

    public string AvatarUrl { get; set; }

    public string Address { get; set; }

    public virtual ICollection<GeneratedVideo> GeneratedVideos { get; set; } = new List<GeneratedVideo>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<OtpToken> OtpTokens { get; set; } = new List<OtpToken>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Prompt> Prompts { get; set; } = new List<Prompt>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual ICollection<Slide> Slides { get; set; } = new List<Slide>();

    public virtual ICollection<UserQuotum> UserQuota { get; set; } = new List<UserQuotum>();
}