// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVision.Models;

public partial class UserQuotum
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string QuotaType { get; set; }

    public int QuotaLimit { get; set; }

    public int QuotaUsed { get; set; }

    public DateTime PeriodStart { get; set; }

    public DateTime PeriodEnd { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User User { get; set; }
}